name: Back-End API Tests

on: [pull_request]

jobs:
    test_project:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - name: Run Django Tests
              shell: pwsh
              run: |
                pip install -r requirements.txt
                Set-Location -Path 'django_backend'
                python manage.py test
              env:
                LANG: C.UTF-8
                LC_ALL: C.UTF-8
